from ohbot import ohbot
import time

# Inicializar Ohbot
ohbot.init()

def cantar_cancion():
    # Movimientos y frases para simular el ritmo de la canción
    ohbot.move(ohbot.EYETILT, 0)
    ohbot.move(ohbot.EYETILT, 10)
    
    # Primera línea: Chipi chipi chapa chapa
    ohbot.move(ohbot.HEADTURN, 8)
    ohbot.wait(0.5)
    ohbot.move(ohbot.HEADNOD, 1)
    ohbot.wait(0.5)
    ohbot.move(ohbot.HEADNOD, 5)
    ohbot.wait(0.5)
    ohbot.move(ohbot.HEADTURN, 3)
    ohbot.move(ohbot.HEADNOD, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 5)  # Movimiento de cabeza
    time.sleep(0.5)
    ohbot.say("Chipi")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 6)
    time.sleep(0.5)
    ohbot.say("Chipi")
    ohbot.move(ohbot.LIDBLINK, 1)
    ohbot.move(ohbot.HEADNOD, 7)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 1)
    ohbot.move(ohbot.HEADNOD, 8)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    time.sleep(0.5)
    ohbot.say("Chapa")
    ohbot.move(ohbot.HEADNOD, 9)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 5)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.HEADNOD, 8)
    ohbot.move(ohbot.LIDBLINK, 0)
    time.sleep(0.5)
    ohbot.say("Chapa")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)

    # Segunda línea: Dubi dubi daba daba
    ohbot.move(ohbot.HEADNOD, 10)
    time.sleep(0.5)
    ohbot.say("Dubi")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 11)
    time.sleep(0.5)
    ohbot.say("Dubi")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 12)
    time.sleep(0.5)
    ohbot.say("Daba")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 5)
    time.sleep(0.5)
    ohbot.say("Daba")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    
    # Tercera línea: Mágico mi dubi dubi
    ohbot.move(ohbot.HEADNOD, 8)
    time.sleep(0.5)
    ohbot.say("Mágico")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 9)
    time.sleep(0.5)
    ohbot.say("Mi")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 10)
    time.sleep(0.5)
    ohbot.say("Dubi")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 11)
    time.sleep(0.5)
    ohbot.say("Dubi")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    
    # Cuarta línea: Bum, bum, bum, bum
    ohbot.move(ohbot.HEADNOD, 12)
    time.sleep(0.5)
    ohbot.say("Bum")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 5)
    time.sleep(0.5)
    ohbot.say("Bum")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 8)
    time.sleep(0.5)
    ohbot.say("Bum")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)
    ohbot.move(ohbot.LIDBLINK, 0)
    ohbot.move(ohbot.HEADNOD, 11)
    time.sleep(0.5)
    ohbot.say("Bum")
    ohbot.move(ohbot.LIDBLINK, 1)
    time.sleep(0.5)

# Llamar a la función para que Ohbot "cante" la canción con movimientos faciales
cantar_cancion()

# Finalizar Ohbot
ohbot.close()
