from ohbot import ohbot
import time

def cantar_cancion():
    print("Chipichapa")
    ohbot.move(ohbot.HEADTURN, 6)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD,9)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN,1)
    ohbot.say("Chipi chipi, chapa chapa")
    ohbot.wait(1)  # Ohbot se despide 
    ohbot.move(ohbot.HEADTURN, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD,9)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN,6)
    ohbot.wait(1)
    ohbot.say("Dubidubi, dabadaba")
    ohbot.move(ohbot.HEADTURN, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD,9)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN,6)
    ohbot.wait(1)
    ohbot.say("Mágico mi dubidubi boom, boom, boom, boom")
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD,9)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN,6)
    ohbot.wait(1)
    ohbot.say("Chipi chipi, chapa chapa")
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD,9)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN,6)
    ohbot.wait(1)
    ohbot.say("Dubidubi, dabadaba")
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD,9)
    ohbot.wait(1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN,6)
    ohbot.wait(1)
    ohbot.say("Mágico mi dubidubi boom")
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN, 1)
    ohbot.wait(1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD, 1)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADNOD,9)
    ohbot.wait(1)
    ohbot.move(ohbot.HEADTURN,6)
    ohbot.wait(1)

    ohbot.say("Espero que te gustara mi magica voz")

def main():
    # Inicializar Ohbot
    ohbot.init()

    # Llamar a la función para que Ohbot "cante" la canción con movimientos faciales
    cantar_cancion()

    # Finalizar Ohbot
    ohbot.close()

if __name__ == "__main__":
    main()
